'use strict';

// Builds a fake Windows user folder with the same layout as a real Claude install (Store version).

const fs = require('fs');
const os = require('os');
const path = require('path');

const IDS = {
  coworkRecord: 'local_11111111-1111-4111-8111-111111111111',
  coworkCli: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
  codeRecord: 'local_22222222-2222-4222-8222-222222222222',
  codeCli: 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
  terminalCli: 'cccccccc-cccc-4ccc-8ccc-cccccccccccc',
  titleOnlyCli: 'dddddddd-dddd-4ddd-8ddd-dddddddddddd',
};

function jsonl(entries) {
  return entries.map((e) => JSON.stringify(e)).join('\n') + '\n';
}

function user(text, timestamp, extra = {}) {
  return { type: 'user', timestamp, sessionId: 's', cwd: 'C:\\proj', message: { role: 'user', content: text }, ...extra };
}

function assistant(text, timestamp) {
  return { type: 'assistant', timestamp, message: { role: 'assistant', content: [{ type: 'text', text }] } };
}

function write(file, content) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content);
}

function makeFakeHome() {
  const home = fs.mkdtempSync(path.join(os.tmpdir(), 'acm-home-'));
  const localAppData = path.join(home, 'AppData', 'Local');
  const appData = path.join(home, 'AppData', 'Roaming');
  const claude = path.join(localAppData, 'Packages', 'Claude_pzs8sxrjxfjjc', 'LocalCache', 'Roaming', 'Claude');
  const projects = path.join(home, '.claude', 'projects');

  // Cowork task: record + its own folder holding the transcript.
  const coworkDir = path.join(claude, 'local-agent-mode-sessions', 'org-1', 'user-1');
  write(path.join(coworkDir, `${IDS.coworkRecord}.json`), JSON.stringify({
    sessionId: IDS.coworkRecord,
    cliSessionId: IDS.coworkCli,
    cwd: '/sessions/happy-otter/mnt/outputs',
    createdAt: Date.parse('2026-09-20T10:00:00Z'),
    lastActivityAt: Date.parse('2026-09-27T09:00:00Z'),
    title: 'Plan the robotics outreach day',
    hostLoopMode: true,
    initialMessage: 'Help me plan an outreach day',
  }));
  write(
    path.join(coworkDir, IDS.coworkRecord, '.claude', 'projects', '-sessions-happy-otter', `${IDS.coworkCli}.jsonl`),
    jsonl([
      user('Help me plan an outreach day', '2026-09-20T10:00:05Z'),
      assistant('Sure, here is a plan.', '2026-09-20T10:00:30Z'),
      user('Add a lunch break', '2026-09-27T08:59:00Z'),
      assistant('Added lunch at 12:30.', '2026-09-27T09:00:00Z'),
    ]),
  );

  // Code session started from the desktop Code tab: record + transcript in ~/.claude/projects.
  write(path.join(claude, 'claude-code-sessions', 'acct-1', 'org-1', `${IDS.codeRecord}.json`), JSON.stringify({
    sessionId: IDS.codeRecord,
    cliSessionId: IDS.codeCli,
    cwd: 'C:\\FTC\\FtcRobotController',
    createdAt: Date.parse('2026-09-28T01:00:00Z'),
    lastActivityAt: Date.parse('2026-09-28T02:00:00Z'),
    title: 'Fix drivetrain encoder',
    titleSource: 'auto',
    isArchived: false,
  }));
  write(path.join(projects, 'C--FTC-FtcRobotController', `${IDS.codeCli}.jsonl`), jsonl([
    user('Why does the encoder read zero?', '2026-09-28T01:00:10Z'),
    { type: 'user', timestamp: '2026-09-28T01:00:20Z', toolUseResult: {}, message: { role: 'user', content: [{ type: 'tool_result', content: 'ok' }] } },
    assistant('The motor port is wrong.', '2026-09-28T01:00:40Z'),
  ]));

  // Session started in a terminal: transcript only, renamed with /rename.
  write(path.join(projects, 'C--Users-me-PycharmProjects-eyeTrack', `${IDS.terminalCli}.jsonl`), jsonl([
    user('<command-name>/model</command-name>', '2026-09-25T05:00:00Z'),
    user('Track the pupils with mediapipe', '2026-09-25T05:01:00Z'),
    user('Caveat: The messages below were generated by the user while running local commands.', '2026-09-25T05:01:01Z', { isMeta: true }),
    assistant('Here is a starting point.', '2026-09-25T05:02:00Z'),
    { type: 'ai-title', aiTitle: 'Pupil tracking with MediaPipe', sessionId: IDS.terminalCli },
    { type: 'custom-title', customTitle: 'Eye tracker v2', sessionId: IDS.terminalCli },
    user('<system-reminder>ignore me</system-reminder>Now smooth the output', '2026-09-26T05:03:00Z'),
  ]) + '{"type":"user","timestamp":"2026-09-26T05:04:00Z","message":{"content":"half-writ');

  // A file with only a title in it (no conversation) should not show up.
  write(path.join(projects, 'C--Users-me-PycharmProjects-eyeTrack', `${IDS.titleOnlyCli}.jsonl`), jsonl([
    { type: 'ai-title', aiTitle: 'Summary only', sessionId: IDS.titleOnlyCli },
  ]));

  return {
    home,
    projects,
    claude,
    options: { home, platform: 'win32', env: { LOCALAPPDATA: localAppData, APPDATA: appData } },
  };
}

function claudeExportConversations() {
  return [
    {
      uuid: '33333333-3333-4333-8333-333333333333',
      name: 'Becoming a developer career path',
      created_at: '2026-09-27T20:00:00.000Z',
      updated_at: '2026-09-27T21:00:00.000Z',
      chat_messages: [
        { sender: 'human', text: 'How do I become a developer?', created_at: '2026-09-27T20:00:00.000Z' },
        { sender: 'assistant', text: '', content: [{ type: 'text', text: 'Start with projects.' }], created_at: '2026-09-27T20:00:10.000Z' },
        { sender: 'human', text: 'What about university?', created_at: '2026-09-27T20:30:00.000Z' },
      ],
    },
    { uuid: '44444444-4444-4444-8444-444444444444', name: '', created_at: '2026-09-01T00:00:00Z', updated_at: '2026-09-01T00:00:00Z', chat_messages: [] },
  ];
}

module.exports = { makeFakeHome, claudeExportConversations, IDS, jsonl, user, assistant, write };
